version: '3.9'

services:
  frontdev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - nuxtdevdeps:/usr/src/app/node_modules
      - ./frontend:/usr/src/app
    env_file:
      - ./frontend/.env
    profiles:
      - local

  backdev:
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - railsdevdeps:/usr/src/app/vendor/bundle
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    profiles:
      - local

  mongo:
    image: mongo:4.4.1-bionic
    env_file:
      - ./backend/.env
    volumes:
      - data:/data/db
    profiles:
      - local
      - if
      - stiback

volumes:
  railsdevdeps:
  nuxtdevdeps:
  data:
